package Inter_Alternativa;

import clases.*;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class Empleado_MAIN extends javax.swing.JFrame {

    private int edit_mode = 0;
    private AccesoSQL acceso;
    private ArrayList<Object> lista;
    private ArrayList<Factura> listaFacturas;
    private boolean firstRun = true;
    
    public Empleado_MAIN() {
        initComponents();
        formatearTabla();
        botonPassword.setVisible(false);
        // Consigo la lista de empleados y la meto en el ArrayList
        acceso = new AccesoSQL();
        lista = new ArrayList<>();
        listaFacturas = new ArrayList<>();
        disableTextField(false);
        inicCombo();
        firstRun = false;
    }
    
    public void formatearTabla() {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(0);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
    }
    
    public void MostrarSQL(String filtroDni) {
        if (!listaFacturas.isEmpty()) {
            listaFacturas.clear();
        }
        listaFacturas = acceso.listadoFactura(filtroDni);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        ((DefaultTableModel)jTable1.getModel()).setNumRows(0);
        Object[] row = new Object[4];
        for (Factura fact : listaFacturas) {
            row[0] = fact.getIdFactura();
            row[1] = fact.getImporte().toEngineeringString()+"€";
            row[2] = R.fechaFormateada(fact.getFecha());
            row[3] = fact.getIdCliente();
            model.addRow(row);
        }
    }
    
    /**************************************************
    FALTA INSERTAR LA FECHA DE ALTA Y BAJA DEL EMPLEADO    
    **************************************************/
    
    public void inicCombo() {
        try {
            lista = acceso.listado("Empleado", "");
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
        try {
            jComboBox1.removeAllItems();
            for (Object o : lista) {
                Empleado emp = (Empleado) o;
                jComboBox1.addItem(emp);
            }
        } catch (NullPointerException e){
            System.out.println(e.getMessage());
            for (Object o : lista) {
                Empleado emp = (Empleado) o;
                jComboBox1.addItem(emp);
            }
        }
        
    }
    
    public void disableTextField(boolean opcion) {
        jTextFieldDni.setEditable(opcion);
        jTextFieldApellidos.setEditable(opcion);
        jTextFieldCorreo.setEditable(opcion);
        jTextFieldNombre.setEditable(opcion);
        jTextFieldTelefono.setEditable(opcion);
        jTextFieldAlta.setEditable(false);
    }
    
    public void emptyfield() {
        jTextFieldDni.setText("");
        jTextFieldNombre.setText("");
        jTextFieldApellidos.setText("");
        jTextFieldTelefono.setText("");
        jTextFieldCorreo.setText("");
        jTextFieldAlta.setText("");
    }
    
    public void resetFrame() {
        emptyfield();
        disableTextField(false);
        jComboBox1.setEnabled(true);
        botonPassword.setEnabled(true);
        botonPassword.setVisible(false);
        edit_mode = 0;
        botonBaja1.setEnabled(true);
        jButtonNuevo.setText("Añadir");
        jButtonEditar.setText("Modificar");
        lista.clear();
        inicCombo();
    }
    
    public void resetFrame(Empleado emp) {
        resetFrame();
        jComboBox1.setSelectedItem(emp);
        jComboBox1.removeItem("Selecciona Empleado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDni3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldDni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jButtonEditar = new javax.swing.JButton();
        botonPassword = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAlta = new javax.swing.JTextField();
        botonBaja1 = new javax.swing.JButton();

        jTextFieldDni3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(248, 241, 242));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 126, 138)), R.getEmpleadoLogado().getNombreCompleto(), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Century Gothic", 0, 18), new java.awt.Color(219, 126, 138))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(clases.R.fuenteRoboto

            (16, clases.R.PLAIN, clases.R.LIGHT)

        );
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleciona empleado" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 126, 138)));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox1MouseReleased(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 180, 40));

        jButtonNuevo.setBackground(new java.awt.Color(225, 225, 225));
        jButtonNuevo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonNuevo.setForeground(new java.awt.Color(219, 126, 138));
        jButtonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/anadir.png"))); // NOI18N
        jButtonNuevo.setText("Añadir");
        jButtonNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 126, 138)));
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 110, 40));

        jTable1.setFont(clases.R.fuenteRoboto

            (18, clases.R.PLAIN, clases.R.LIGHT)
        );
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Factura", "Importe", "Fecha", "Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 550, 232));

        jTextFieldDni.setFont(clases.R.fuenteRoboto

            (18, clases.R.PLAIN, clases.R.LIGHT)
        );
        jTextFieldDni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 126, 138)));
        jPanel1.add(jTextFieldDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 130, 35));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel1.setText("DNI:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 35));

        jTextFieldNombre.setFont(clases.R.fuenteRoboto

            (18, clases.R.PLAIN, clases.R.LIGHT)
        );
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 126, 138)));
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 230, 35));

        jTextFieldApellidos.setFont(clases.R.fuenteRoboto

            (18, clases.R.PLAIN, clases.R.LIGHT)
        );
        jTextFieldApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 126, 138)));
        jPanel1.add(jTextFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 230, 35));

        jTextFieldTelefono.setFont(clases.R.fuenteRoboto

            (18, clases.R.PLAIN, clases.R.LIGHT)
        );
        jTextFieldTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 126, 138)));
        jPanel1.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 130, 35));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, 35));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setText("Apellidos:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, 35));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel4.setText("Teléfono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 35));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel5.setText("Correo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 35));

        jTextFieldCorreo.setFont(clases.R.fuenteRoboto

            (18, clases.R.PLAIN, clases.R.LIGHT)
        );
        jTextFieldCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 126, 138)));
        jPanel1.add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 470, 35));

        jButtonEditar.setBackground(new java.awt.Color(225, 225, 225));
        jButtonEditar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(219, 126, 138));
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lapiztiny.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 126, 138)));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 120, 40));

        botonPassword.setBackground(new java.awt.Color(225, 225, 225));
        botonPassword.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botonPassword.setForeground(new java.awt.Color(219, 126, 138));
        botonPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/password-Normal.png"))); // NOI18N
        botonPassword.setText("Restablecer Contraseña");
        botonPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 126, 138)));
        botonPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(botonPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 230, 35));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel6.setText("Alta:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 35));

        jTextFieldAlta.setFont(clases.R.fuenteRoboto

            (18, clases.R.PLAIN, clases.R.LIGHT)
        );
        jTextFieldAlta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 126, 138)));
        jTextFieldAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAltaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 130, 35));

        botonBaja1.setBackground(new java.awt.Color(225, 225, 225));
        botonBaja1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botonBaja1.setForeground(new java.awt.Color(219, 126, 138));
        botonBaja1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/volver-Normal.png"))); // NOI18N
        botonBaja1.setText("Atrás");
        botonBaja1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 126, 138)));
        botonBaja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBaja1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonBaja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getItemCount()==0) {
            jComboBox1.addItem("Selecciona Empleado");
            jComboBox1.setSelectedIndex(0);
        } else if (jComboBox1.getSelectedItem() instanceof String || firstRun) {
            emptyfield();
        } else {
            System.out.println(jComboBox1.getSelectedItem());
            Empleado emp = (Empleado) jComboBox1.getSelectedItem();
            jTextFieldDni.setText(emp.getDni());
            jTextFieldNombre.setText(emp.getNombre());
            jTextFieldApellidos.setText(emp.getApellidos());
            jTextFieldTelefono.setText(String.valueOf(emp.getTelefono()));
            jTextFieldCorreo.setText(emp.getCorreo());
            jTextFieldAlta.setText(R.fechaFormateadaCorta(emp.getFechaAlta()));
            MostrarSQL(emp.getDni());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered

    }//GEN-LAST:event_jComboBox1MouseEntered

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        Empleado emp;
        switch (edit_mode){
        
        case 0: //AÑADIR ------------------------------------------------------//
        
            edit_mode = 1;
            emptyfield();
            disableTextField(true);
            jComboBox1.setEnabled(false);
            jButtonNuevo.setText("Guardar");
            jButtonEditar.setText("Cancelar");
            botonBaja1.setEnabled(false);
            break;
            
        case 1: //Adición Empleado ON -----------------------------------------//
            
            emp = new Empleado(
                jTextFieldNombre.getText(),
                jTextFieldApellidos.getText(),
                jTextFieldCorreo.getText(),
                Integer.parseInt(jTextFieldTelefono.getText()),
                jTextFieldDni.getText()
                );
            
            if (acceso.insertEmpleado(emp)==1){
                resetFrame(emp);
                JOptionPane.showMessageDialog(null, "Empleado creado correctamente", "Crear Empleado", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo insertar el empleado", "Error 052", JOptionPane.ERROR_MESSAGE);
            }
            break;
            
        case 2: //Edición Empleado --------------------------------------------//
            Empleado empleado = new Empleado(
                    jTextFieldNombre.getText(),
                    jTextFieldApellidos.getText(),
                    jTextFieldCorreo.getText(),
                    Integer.valueOf(jTextFieldTelefono.getText()),
                    jTextFieldDni.getText());
            if (acceso.updateEmpleado(empleado)){
                resetFrame(empleado);
            }
            break;
    }


    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        
        switch (edit_mode){
            
            case 0: //Adición Empleado OFF ------------------------------------//
                
                if (jComboBox1.getSelectedItem() instanceof String){
                    JOptionPane.showMessageDialog(null,
                        "Tienes que seleccionar un usuario primero!");
                } else {
                    Empleado emp = (Empleado) jComboBox1.getSelectedItem();
                    edit_mode = 2;
                    botonBaja1.setEnabled(false);
                    botonPassword.setVisible(true);
                    botonPassword.setEnabled(true);
                    jComboBox1.setEnabled(false);
                    disableTextField(true);
                    jTextFieldApellidos.setText(emp.getApellidos());
                    jTextFieldCorreo.setText(emp.getCorreo());
                    jTextFieldNombre.setText(emp.getNombre());
                    jTextFieldTelefono.setText(String.valueOf(emp.getTelefono()));
                    jButtonNuevo.setText("Guardar");
                    jButtonEditar.setText("Cancelar");                    
                }
                break;
                
            case 1: //CANCELAR (EN AÑADIR) -------------------------------------//
                
                resetFrame();
                break;
                
            case 2: //Edición Empleado ----------------------------------------//
                
                resetFrame((Empleado)jComboBox1.getSelectedItem());
                break;
                            
        }
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void botonPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPasswordActionPerformed
        new PopupPassword(this,(Empleado)jComboBox1.getSelectedItem(),acceso).setVisible(true);
    }//GEN-LAST:event_botonPasswordActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String idFact = model.getValueAt(i,0).toString();
        Factura fact = new Factura();
        try {
            fact = (Factura) acceso.listadoID("Factura", idFact);
        } catch (SQLException ex) {
            System.err.println("Error al procesar la Factura.");
        }
        acceso.cerrar();
        new Factura_DETAIL(fact,1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseReleased
        
    }//GEN-LAST:event_jComboBox1MouseReleased

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void botonBaja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBaja1ActionPerformed
        acceso.cerrar();
        new Menu_GEST().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonBaja1ActionPerformed

    private void jTextFieldAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleado_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleado_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleado_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleado_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleado_MAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBaja1;
    private javax.swing.JButton botonPassword;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JComboBox<Object> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAlta;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldDni3;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
