/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inter_Alternativa;

import clases.*;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kaien
 */
public class Producto_EDIT extends javax.swing.JFrame {

    private String id;
    AccesoSQL acceso;
    Producto producto;
    
    /**
     * Creates new form Inter_Producto_edit
     * @param id
     */
    public Producto_EDIT(String id) {
        initComponents();
        camposNoEditables(false);
        
        this.id = id;
        acceso = new AccesoSQL();
        try {
            producto = (Producto) acceso.listadoID("Producto",id);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } 
        campoIDproducto.setText(id);
        campoTipo.setText(producto.getTipo());
        campoMarca.setText(producto.getMarca());
        campoModelo.setText(producto.getModelo());
        campoPrecio.setText(String.valueOf(producto.getPrecioUnitario()));
        campoObservaciones.setText(producto.getObservaciones());
    }

    private Producto_EDIT() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void camposNoEditables(boolean Opcion) {
        campoIDproducto.setEditable(false);
        campoTipo.setEditable(Opcion);
        campoMarca.setEditable(Opcion);
        campoModelo.setEditable(Opcion);
        campoPrecio.setEditable(Opcion);
        campoObservaciones.setEditable(Opcion);                
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_Busqueda1 = new javax.swing.JTextField();
        jTextField_Busqueda6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botonAdd1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelIDproducto = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        etqTipo = new javax.swing.JLabel();
        etqMarca = new javax.swing.JLabel();
        etqModelo = new javax.swing.JLabel();
        etqPrecio = new javax.swing.JLabel();
        etqObservaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoObservaciones = new javax.swing.JTextArea();
        campoTipo = new javax.swing.JTextField();
        campoMarca = new javax.swing.JTextField();
        campoModelo = new javax.swing.JTextField();
        campoPrecio = new javax.swing.JTextField();
        botonEliminar = new javax.swing.JButton();
        campoIDproducto = new javax.swing.JTextField();
        checkModificar = new javax.swing.JCheckBox();

        jTextField_Busqueda1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jTextField_Busqueda6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_Busqueda6.setText("608505377");
        jTextField_Busqueda6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Busqueda6ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Cliente desde \"Fecha\"");

        botonAdd1.setBackground(new java.awt.Color(225, 225, 225));
        botonAdd1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botonAdd1.setForeground(new java.awt.Color(219, 126, 138));
        botonAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdd1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(248, 241, 242));

        jLabelIDproducto.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabelIDproducto.setForeground(new java.awt.Color(219, 126, 138));
        jLabelIDproducto.setText("ID Producto:");

        botonCancelar.setBackground(new java.awt.Color(225, 225, 225));
        botonCancelar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(219, 126, 138));
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/salir-Normal.png"))); // NOI18N
        botonCancelar.setText("Atrás");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonModificar.setBackground(new java.awt.Color(225, 225, 225));
        botonModificar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botonModificar.setForeground(new java.awt.Color(219, 126, 138));
        botonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lapiz.png"))); // NOI18N
        botonModificar.setText("Guardar");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        etqTipo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        etqTipo.setForeground(new java.awt.Color(219, 126, 138));
        etqTipo.setText("Tipo:");

        etqMarca.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        etqMarca.setForeground(new java.awt.Color(219, 126, 138));
        etqMarca.setText("Marca:");

        etqModelo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        etqModelo.setForeground(new java.awt.Color(219, 126, 138));
        etqModelo.setText("Modelo:");

        etqPrecio.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        etqPrecio.setForeground(new java.awt.Color(219, 126, 138));
        etqPrecio.setText("Precio:");

        etqObservaciones.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        etqObservaciones.setForeground(new java.awt.Color(219, 126, 138));
        etqObservaciones.setText("Observaciones:");

        campoObservaciones.setColumns(20);
        campoObservaciones.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        campoObservaciones.setRows(5);
        jScrollPane1.setViewportView(campoObservaciones);

        campoTipo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        campoMarca.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        campoModelo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        campoPrecio.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        botonEliminar.setBackground(new java.awt.Color(225, 225, 225));
        botonEliminar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(219, 126, 138));
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cerrar.png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        campoIDproducto.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        checkModificar.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        checkModificar.setForeground(new java.awt.Color(219, 126, 138));
        checkModificar.setText("Modificar Producto");
        checkModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelIDproducto)
                        .addGap(18, 18, 18)
                        .addComponent(campoIDproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etqPrecio)
                        .addGap(18, 18, 18)
                        .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(etqObservaciones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                                .addComponent(checkModificar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(etqMarca)
                                            .addComponent(etqTipo))
                                        .addGap(26, 26, 26))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(etqModelo)
                                        .addGap(19, 19, 19)))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                                    .addComponent(campoTipo)
                                    .addComponent(campoModelo)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etqPrecio)
                    .addComponent(campoIDproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIDproducto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqTipo)
                    .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqMarca)
                    .addComponent(campoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqModelo)
                    .addComponent(campoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(checkModificar)
                    .addComponent(etqObservaciones))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Busqueda6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Busqueda6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Busqueda6ActionPerformed

    private void botonAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAdd1ActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        acceso.cerrar();
        new Producto_BUSQ().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        if (checkModificar.isSelected() == true){
            String query = 
                "UPDATE `Producto` SET `tipo`='"+campoTipo.getText()+"',`marca`='"+campoMarca.getText()+
                "',`modelo`='"+campoModelo.getText()+"',`precioUnitario`="+campoPrecio.getText()+
                ",`observaciones`='"+campoObservaciones.getText()+"' WHERE `idProducto` = "+this.id;
            acceso.UpdateSql(query);
        } else {
            JOptionPane.showMessageDialog(null, "Debe de marcar la opción modificar");
        }
        
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar este producto?", "¡Atención!", JOptionPane.YES_NO_OPTION);
            if (resp == 0){
                String query = "DELETE FROM `Producto` WHERE  `idProducto` = " + this.id;
                acceso.UpdateSql(query);
                new Producto_BUSQ().setVisible(true);
                this.dispose();    
            } else {
                JOptionPane.showMessageDialog(null, "No se ha eliminado el producto");
            }        
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void checkModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkModificarActionPerformed
        if (checkModificar.isSelected() == true){
            camposNoEditables(true);
        } else {
            camposNoEditables(false);
        }
    }//GEN-LAST:event_checkModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente_EDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente_EDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente_EDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente_EDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Producto_EDIT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdd1;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JTextField campoIDproducto;
    private javax.swing.JTextField campoMarca;
    private javax.swing.JTextField campoModelo;
    private javax.swing.JTextArea campoObservaciones;
    private javax.swing.JTextField campoPrecio;
    private javax.swing.JTextField campoTipo;
    private javax.swing.JCheckBox checkModificar;
    private javax.swing.JLabel etqMarca;
    private javax.swing.JLabel etqModelo;
    private javax.swing.JLabel etqObservaciones;
    private javax.swing.JLabel etqPrecio;
    private javax.swing.JLabel etqTipo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelIDproducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_Busqueda1;
    private javax.swing.JTextField jTextField_Busqueda6;
    // End of variables declaration//GEN-END:variables
}
