CREATE TABLE Producto
(
idProducto MEDIUMINT ZEROFILL PRIMARY KEY AUTO_INCREMENT,
marca VARCHAR (30) NOT NULL,
modelo VARCHAR (50) NOT NULL,
precioUnitario SMALLINT (5) NOT NULL CHECK (precioUnitario>=0)
);