CREATE TABLE Factura
(
idFactura MEDIUMINT ZEROFILL PRIMARY KEY AUTO_INCREMENT,
idCliente MEDIUMINT NOT NULL REFERENCES Cliente(idCliente) ON DELETE SET NULL,
dniEmpleado VARCHAR (9) NOT NULL REFERENCES Empleado(dni) ON UPDATE CASCADE,
fecha DATETIME DEFAULT NOW(),
importe SMALLINT NOT NULL
);