CREATE TABLE Linea
(
idLinea INT ZEROFILL PRIMARY KEY AUTO_INCREMENT,
idFactura MEDIUMINT ZEROFILL NOT NULL REFERENCES Factura(idFactura),
idProducto MEDIUMINT ZEROFILL NOT NULL REFERENCES Producto(idProducto),
idPromocion MEDIUMINT ZEROFILL NOT NULL REFERENCES Promocion(idPromocion),
cantidad SMALLINT NOT NULL CHECK (cantidad>0),
importeLinea FLOAT NOT NULL
);